# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: R -q -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: R -q -e "getOption('repos')"
  - cmd: R -q -e "install.packages('remotes'); remotes::install_github('ropenscilabs/tic'); tic::prepare_all_stages()"

cache:
  # clearing the cache: https://github.com/appveyor/ci/issues/985
  # change .appveyor_clear_cache.txt to invalidate cache
  - C:\RLibrary -> .appveyor_clear_cache.txt

before_build: R -q -e "tic::before_install()"
build_script: R -q -e "tic::install()"
after_build: R -q -e "tic::after_install()"
before_test: R -q -e "tic::before_script()"
test_script: R -q -e "tic::script()"
on_success: R -q -e "try(tic::after_success(), silent = TRUE)"
on_failure: R -q -e "tic::after_failure()"
before_deploy: R -q -e "tic::before_deploy()"
deploy_script: R -q -e "tic::deploy()"
after_deploy: R -q -e "tic::after_deploy()"
on_finish: R -q -e "tic::after_script()"

# Adapt as necessary starting from here

environment:
  PKGTYPE: binary
  matrix:
    - R_VERSION: release
      R_ARCH: x64

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
